Make most of the files for check_avail and reset_unavail optional

diff --git a/reset_unavail b/reset_unavail
--- a/reset_unavail
+++ b/reset_unavail
@@ -1,17 +1,29 @@
 #!/bin/bash
 
 DIR=`realpath "$0"`
-TS=0
-SEC=`cat "$DIR/limit"`
+[ -f "$DIR/$1.timestamp" ] && TS=`cat "$DIR/$1.timestamp"` || TS=0
+[ -f "$DIR/limit" ] && SEC=`cat "$DIR/limit"` || SEC=3600
 LIM=$((`/usr/bin/date +%s` - $SEC))
-[ -f "$DIR/$1.timestamp" ] && TS=`cat "$DIR/$1.timestamp"`
 if [ $TS -le $LIM ]
 then
     BMC=`cat "$DIR/$1.bmc"`
-    /usr/bin/ssh -i "$DIR/$BMC.pk" -l `cat "$DIR/$BMC.user"` $BMC `cat "$DIR/$BMC.command"`
-    echo "Reset server $1 at `date`" >> "$DIR/$1.log"
-    [ -f "$DIR/https_proxy" ] && export https_proxy=`cat "$DIR/https_proxy"`
-    [ -f "$DIR/webhook" ] && /usr/bin/curl --data "{ \"content\": \"Notice: Server $1 was unavailable at `date`, performed cold reset.\" }" -H "Content-Type: application/json" -X POST `cat "$DIR/webhook"`
+    if [ "$BMC" ]
+    then
+        [ -f "$DIR/$BMC.user" ] && USER=`cat "$DIR/$BMC.pk"` || USER="root"
+        [ -f "$DIR/$BMC.command" ] && CMD=`cat "$DIR/$BMC.pk"` || CMD="server_reset"
+        if [ -f "$DIR/$BMC.pk" ]
+        then
+            /usr/bin/ssh -i "$DIR/$BMC.pk" -l "$USER" "$BMC" "$CMD"
+        else
+            /usr/bin/ssh -l "$USER" "$BMC" "$CMD"
+        fi
+        echo "Reset server $1 at `date`" >> "$DIR/$1.log"
+        [ -f "$DIR/https_proxy" ] && export https_proxy=`cat "$DIR/https_proxy"`
+        [ -f "$DIR/webhook" ] && /usr/bin/curl --data "{ \"content\": \"Notice: Server $1 was unavailable at `date`, performed cold reset.\" }" -H "Content-Type: application/json" -X POST `cat "$DIR/webhook"`
+    else
+        echo "Unable to reset server $1 at `date`: no BMC is known for it!" >> "$DIR/$1.log"
+        exit 1
+    fi
 else
     echo "Server $1 is alive at `date`" >> "$DIR/$1.log"
 fi
